{"error": null, "issues": [{"address": 2708, "code": " addr", "debug": "calldata_SuperOwners_32 + 4: 0xb135d1e4a0020a903239033aa9b45a69384c906b52a71e0575829626809581fd\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_SuperOwners_4: 0xa7e6e147bc0ca40011bf9bbaadf7593cb8cc90b17cb7d73775f0d8eb1435e9c1\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xb135d1e4a0020a903239033aa9b45a69384c906b52a71e0575829626809581fd\ncalldata_SuperOwners_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_SuperOwners_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_SuperOwners: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transfer(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Coinrace-5.sol", "function": "transfer(address,uint256)", "lineno": 94, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2721, "code": "owner1;\n    ad", "debug": "The exception is triggered under the following conditions:\n\ncalldata_SuperOwners_32 + 4: 0x950dff78e666f73fd36ffedf5fe656f42f732f95edbafb7bf77fedeee4c653a9\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_SuperOwners_4: 0xf71ca024c4e4c48edb080090575702d73908a831c1b8c07b8480010000f10f3b\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x950dff78e666f73fd36ffedf5fe656f42f732f95edbafb7bf77fedeee4c653a9\ncalldata_SuperOwners_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_SuperOwners_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_SuperOwners: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Coinrace-5.sol", "function": "transfer(address,uint256)", "lineno": 94, "title": "Exception state", "type": "Informational"}], "success": true}
