{"error": null, "issues": [{"address": 914, "code": " public state; \n    addre", "debug": "The exception is triggered under the following conditions:\n\nstorage_11: 0xfe00\ncalldata_Lucky50_0: 0xc19d93fb00000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "_function_0xc19d93fb", "lineno": 13, "title": "Exception state", "type": "Informational"}, {"address": 1352, "code": " already Running!\");\n       ", "debug": "The exception is triggered under the following conditions:\n\nstorage_11: 0xfe00\ncaller: 0xfe\ncalldata_Lucky50_0: 0x46f7da200000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "resume()", "lineno": 38, "title": "Exception state", "type": "Informational"}, {"address": 1522, "code": "50] public previouswinners;\n    ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lucky50_4: 0x32\ncalldata_Lucky50_0: 0x3840a02a00000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "_function_0x3840a02a", "lineno": 7, "title": "Exception state", "type": "Informational"}, {"address": 1679, "code": "ng!\");\n       owner.transfer", "debug": "The exception is triggered under the following conditions:\n\nstorage_11: 0xfe00\ncaller: 0xfe\ncalldata_Lucky50_0: 0x3ccfd60b00000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "withdraw()", "lineno": 44, "title": "Exception state", "type": "Informational"}, {"address": 1902, "code": "function enter(uint8 number)", "debug": "SOLVER OUTPUT:\nstorage_11: 0x100\ncaller: 0x1\ncalldata_Lucky50_0: 0x3ccfd60b00000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "In the function `withdraw()` a non-zero amount of Ether is sent to an address taken from storage slot 11.\nThere is a check on storage index 11. This storage slot can be written to by calling the function `enter(uint8)`.\n\nThere is a check on storage index 11. This storage slot can be written to by calling the function `enter(uint8)`.\nThere is a check on storage index 11. This storage slot can be written to by calling the function `enter(uint8)`.\nThere is a check on storage index 11. This storage slot can be written to by calling the function `enter(uint8)`.", "filename": "/temp/ETH_Game-2.sol", "function": "withdraw()", "lineno": 48, "title": "Ether send", "type": "Warning"}, {"address": 1902, "code": "function enter(uint8 number)", "debug": "", "description": "A possible transaction order independence vulnerability exists in function withdraw(). The value or direction of the call statement is determined from a tainted storage location", "filename": "/temp/ETH_Game-2.sol", "function": "withdraw()", "lineno": 48, "title": "Transaction order dependence", "type": "Warning"}, {"address": 2060, "code": "number before yo", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lucky50_4: 0x65\ncalldata_Lucky50_0: 0x4aa1673700000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "enter(uint8)", "lineno": 49, "title": "Exception state", "type": "Informational"}, {"address": 2313, "code": ";\n        require(msg.value == ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lucky50_4: 0x20\nstorage_11: 0xfe00\n256_EXP_Concat(0, Extract(4, 0, calldata_Lucky50_4)): 0x1\nstorage_Concat(0, Extract(7, 5, calldata_Lucky50_4)) + 5: 0x0\ncalldata_Lucky50_0: 0x4aa1673700000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "enter(uint8)", "lineno": 51, "title": "Exception state", "type": "Informational"}, {"address": 2574, "code": "icipant\n        numbe", "debug": "calldata_Lucky50_4: 0x10\nstorage_Concat(0, Extract(7, 5, calldata_Lucky50_4)) + 5: 0x307c80fe5ff9dfff8fc07dffffffdfc0ffa6e4f803ff01e195b00001601e0058\nstorage_11: 0x0\n256_EXP_Concat(0, Extract(4, 0, calldata_Lucky50_4)): 0xd0104820444102084a02c58457a004200020040c000000019100000500040042\ncalldata_Lucky50_0: 0x4aa1673700000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\nstorage_9: 0x0\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `enter(uint8)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/ETH_Game-2.sol", "function": "enter(uint8)", "lineno": 60, "title": "Integer Overflow ", "type": "Warning"}, {"address": 2860, "code": "hed,\"Game is Running,Cannot ", "debug": "The exception is triggered under the following conditions:\n\nstorage_11: 0xfe00\ncaller: 0xfe\ncalldata_Lucky50_0: 0x8431700800000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "setprice(uint256,uint256)", "lineno": 26, "title": "Exception state", "type": "Informational"}, {"address": 3127, "code": "ame is already Paused!\");\n   ", "debug": "The exception is triggered under the following conditions:\n\nstorage_11: 0xfe00\ncaller: 0xfe\ncalldata_Lucky50_0: 0x8456cb5900000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "pause()", "lineno": 33, "title": "Exception state", "type": "Informational"}, {"address": 3335, "code": "1] public occupied;\n    u", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lucky50_4: 0x65\ncalldata_Lucky50_0: 0x92b0458500000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "_function_0x92b04585", "lineno": 8, "title": "Exception state", "type": "Informational"}, {"address": 3382, "code": "[50] public winners;\n   ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lucky50_4: 0x32\ncalldata_Lucky50_0: 0xa2fb117500000000000000000000000000000000000000000000000000000000\ncalldatasize_Lucky50: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ETH_Game-2.sol", "function": "_function_0xa2fb1175", "lineno": 6, "title": "Exception state", "type": "Informational"}], "success": true}
