{"error": null, "issues": [{"address": 143, "code": "ate numberAllocator;\n    bool[10] i", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Random32BigInteger_4: 0xa\ncalldata_Random32BigInteger_0: 0xca441b8500000000000000000000000000000000000000000000000000000000\ncalldatasize_Random32BigInteger: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/EthJackpot-0.sol", "function": "_function_0xca441b85", "lineno": 58, "title": "Exception state", "type": "Informational"}], "success": true}
