{"error": null, "issues": [{"address": 3553, "code": "e = finalPrice;\n            LogFinalizeMatch(matchId, finalPrice);\n        }\n\n", "debug": "", "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.", "filename": "/temp/SportCrypt-0.sol", "function": "claim(uint256,uint8,bytes32,bytes32,uint8)", "lineno": 219, "title": "Unchecked CALL return value", "type": "Informational"}, {"address": 3924, "code": " uint(delta));\n", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x8000000000000000000000000000000000000000000000000000000000000000\ncalldata_SportCrypt_32 + 4: 0xff\nstorage_1 + keccac_calldata_SportCrypt_4: 0xff00\ncalldata_SportCrypt_0: 0x641bbdfe00000000000000000000000000000000000000000000000000000000\ncalldatasize_SportCrypt: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `claim(uint256,uint8,bytes32,bytes32,uint8)`.\nThe subtraction may result in a value < 0.", "filename": "/temp/SportCrypt-0.sol", "function": "claim(uint256,uint8,bytes32,bytes32,uint8)", "lineno": 241, "title": "Integer Underflow", "type": "Warning"}, {"address": 7653, "code": "      if (position ", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x8000000000000000000000000000000000000000000000000000000000000000\ncalldata_SportCrypt_32 + 4: 0xff\nstorage_1 + keccac_calldata_SportCrypt_4: 0xff00\ncalldata_SportCrypt_0: 0x641bbdfe00000000000000000000000000000000000000000000000000000000\ncalldatasize_SportCrypt: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/SportCrypt-0.sol", "function": "claim(uint256,uint8,bytes32,bytes32,uint8)", "lineno": 283, "title": "Exception state", "type": "Informational"}, {"address": 10403, "code": "rn a >= b ? a : b;\n    }\n\n  ", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x4404000441ffbfffa7ffffffff4fe9ff2927fd55470440013081fcd8dff07bf\ncalldata_SportCrypt_32 + 4: 0xf2\nstorage_1 + keccac_calldata_SportCrypt_4: 0xf200\ncalldata_SportCrypt_0: 0x641bbdfe00000000000000000000000000000000000000000000000000000000\ncalldatasize_SportCrypt: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/SportCrypt-0.sol", "function": "claim(uint256,uint8,bytes32,bytes32,uint8)", "lineno": 521, "title": "Exception state", "type": "Informational"}, {"address": 10606, "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xb2c81e3be60b809eebca250ae5f3958de8241f3c0942692d3cecd1fd00743211\ncallvalue: 0x93931c13e507cbbcbf74d9eee4fb920eeaef84aa5110428da2eddb017d5ebcdd\ncalldata_SportCrypt_0: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_SportCrypt: 0x4\n", "description": "A possible integer overflow exists in the function `deposit()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/SportCrypt-0.sol", "function": "deposit()", "lineno": 527, "title": "Integer Overflow ", "type": "Warning"}, {"address": 10631, "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xc63a21246c99b000ea0030728005ea6909080a424a47ca48059be3c0ff803205\ncallvalue: 0xd2bd697b67b8b7eebcef8ebaf405ca6a0b728a06c347eda3d5dbebfeffbdb977\ncalldata_SportCrypt_0: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_SportCrypt: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/SportCrypt-0.sol", "function": "deposit()", "lineno": 527, "title": "Exception state", "type": "Informational"}], "success": true}
