{"error": null, "issues": [{"address": 1720, "code": "ctive = false;\n    }\n\n    // Th", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/temp/ZethrGame-1.sol", "function": "ownerKill()", "lineno": 235, "title": "Message call to external contract", "type": "Informational"}, {"address": 1720, "code": "ctive = false;\n    }\n\n    // Th", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 1912\n", "filename": "/temp/ZethrGame-1.sol", "function": "ownerKill()", "lineno": 235, "title": "Multiple Calls", "type": "Information"}, {"address": 1912, "code": " onlyOwner {\n        gameActive = false;\n    }\n\n    // The", "debug": "", "description": "This contract executes a message call to to another contract. Make sure that the called contract is trusted and does not execute user-supplied code.", "filename": "/temp/ZethrGame-1.sol", "function": "ownerKill()", "lineno": 234, "title": "Message call to external contract", "type": "Informational"}, {"address": 4137, "debug": "storage_4: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldata_Zethell_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_9: 0x0\ncalldata_Zethell_4: 0x0\ncalldata_Zethell_0: 0xc0ee0b8a00000000000000000000000000000000000000000000000000000000\ncalldatasize_Zethell: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `tokenFallback(address,uint256,bytes)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/ZethrGame-1.sol", "function": "tokenFallback(address,uint256,bytes)", "lineno": 305, "title": "Integer Overflow ", "type": "Warning"}, {"address": 4150, "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0x1\ncalldata_Zethell_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_9: 0x0\ncalldata_Zethell_4: 0x0\ncalldata_Zethell_0: 0xc0ee0b8a00000000000000000000000000000000000000000000000000000000\ncalldatasize_Zethell: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ZethrGame-1.sol", "function": "tokenFallback(address,uint256,bytes)", "lineno": 305, "title": "Exception state", "type": "Informational"}, {"address": 4174, "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0x0\nstorage_2: 0x1\nstorage_1: 0x0\nstorage_0: 0xffffffffffffffffffffffffffffffffffffffff00\ncaller: 0x0\ncalldata_Zethell_0: 0xf41f4b1000000000000000000000000000000000000000000000000000000000\ncalldatasize_Zethell: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/ZethrGame-1.sol", "function": "retrieveHouseTake()", "lineno": 305, "title": "Exception state", "type": "Informational"}], "success": true}
