{"error": null, "issues": [{"address": 492, "code": ";\n\n/**\n * @title O", "debug": "callvalue: 0x0\nstorage_13: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0x0\nstorage_1: 0x0\ncalldatasize_distribution: 0x3\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Fast10ETH-0.sol", "function": "fallback", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 717, "code": "  emit OnDepositeR", "debug": "callvalue: 0x0\nstorage_6: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0x0\nstorage_1: 0x0\ncalldatasize_distribution: 0x3\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Fast10ETH-0.sol", "function": "fallback", "lineno": 222, "title": "Integer Overflow ", "type": "Warning"}, {"address": 797, "code": "  \n    function dist", "debug": "callvalue: 0xfffffffffffffffffffffffffffffffffffffffffffffffbffffffffffdfffff\nstorage_13: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0xfffffffffffffffffffffffffffffffffffffffffffffffbffffffffffdfffff\nstorage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffbffffffffffdfffff\ncalldatasize_distribution: 0x3\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\n", "description": "A possible integer underflow exists in the function `fallback`.\nThe subtraction may result in a value < 0.", "filename": "/temp/Fast10ETH-0.sol", "function": "fallback", "lineno": 224, "title": "Integer Underflow", "type": "Warning"}, {"address": 804, "code": ";\n\n/**\n * @title O", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncallvalue: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldatasize_distribution: 0x3\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Fast10ETH-0.sol", "function": "fallback", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3078, "code": "ger m", "debug": "storage_4: 0x2c60dbd9ee02041b8124fb179125c4475ec6a654a9166569034d4e6765dbdfdb\ncallvalue: 0xeb5f10f9e86264d38426db541f0ddab51e64ab70fda005c01eade2f53e1f5522\nstorage_2: 0xeb5f10f9e86264d38426db541f0ddab51e64ab70fda005c01eade2f53e1f5522\nstorage_1: 0xeb5f10f9e86264d38426db541f0ddab51e64ab70fda005c01eade2f53e1f5522\ncalldatasize_distribution: 0x3\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Fast10ETH-0.sol", "function": "fallback", "lineno": 131, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3404, "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x0\ncalldata_distribution_0: 0x2646b17600000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getPaimentStatus(address,uint256)", "lineno": 303, "title": "Exception state", "type": "Informational"}, {"address": 3427, "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4 +\ncalldata_distribution_32 + 4: 0x0\nstorage_13: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x1\ncalldata_distribution_0: 0x2646b17600000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getPaimentStatus(address,uint256)", "lineno": 303, "title": "Exception state", "type": "Informational"}, {"address": 3492, "code": "ire (msg.sender == distribu", "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_4: 0x0\nstorage_13: 0x0\ncalldata_distribution_0: 0x3f66d16000000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "_function_0x3f66d160", "lineno": 174, "title": "Exception state", "type": "Informational"}, {"address": 3599, "code": "on setDistributorAddress(address newDistributo", "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x0\ncalldata_distribution_0: 0x466c01b800000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "_function_0x466c01b8", "lineno": 178, "title": "Exception state", "type": "Informational"}, {"address": 3703, "code": "blic view returns(uint) {\n        ret", "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x0\ncalldata_distribution_0: 0x6071105800000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getUserDeposit(address,uint256)", "lineno": 291, "title": "Exception state", "type": "Informational"}, {"address": 3726, "code": "Number) public view returns(uint) {\n        retu", "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4 +\ncalldata_distribution_32 + 4: 0x0\nstorage_13: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x1\ncalldata_distribution_0: 0x6071105800000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getUserDeposit(address,uint256)", "lineno": 291, "title": "Exception state", "type": "Informational"}, {"address": 4075, "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x0\ncalldata_distribution_0: 0x631b052000000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getPaimentTime(address,uint256)", "lineno": 303, "title": "Exception state", "type": "Informational"}, {"address": 4098, "code": " }\n}", "debug": "The exception is triggered under the following conditions:\n\ncalldata_distribution_32 + 4: 0x0\nstorage_keccac_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4 +\ncalldata_distribution_32 + 4: 0x0\nstorage_13: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_distribution_4: 0x1\ncalldata_distribution_0: 0x631b052000000000000000000000000000000000000000000000000000000000\ncalldatasize_distribution: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Fast10ETH-0.sol", "function": "getPaimentTime(address,uint256)", "lineno": 302, "title": "Exception state", "type": "Informational"}], "success": true}
