{"error": null, "issues": [{"address": 214, "code": ";\n  }", "debug": "calldata_TeamAmberInterface_4: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldata_TeamAmberInterface_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\ncalldata_TeamAmberInterface_0: 0x3ce6c5500000000000000000000000000000000000000000000000000000000\ncalldatasize_TeamAmberInterface: 0x4\n", "description": "A possible integer overflow exists in the function `roundUp(uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Amber_Game-0.sol", "function": "roundUp(uint256,uint256)", "lineno": 42, "title": "Integer Overflow ", "type": "Warning"}, {"address": 227, "code": "ction roundUp(", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TeamAmberInterface_4: 0x1\ncalldata_TeamAmberInterface_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TeamAmberInterface_0: 0x3ce6c5500000000000000000000000000000000000000000000000000000000\ncalldatasize_TeamAmberInterface: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Amber_Game-0.sol", "function": "roundUp(uint256,uint256)", "lineno": 45, "title": "Exception state", "type": "Informational"}, {"address": 251, "code": "  }\n\n  functio", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TeamAmberInterface_4: 0x0\ncalldata_TeamAmberInterface_32 + 4: 0x0\ncalldata_TeamAmberInterface_0: 0x3ce6c5500000000000000000000000000000000000000000000000000000000\ncalldatasize_TeamAmberInterface: 0x4\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Amber_Game-0.sol", "function": "roundUp(uint256,uint256)", "lineno": 37, "title": "Exception state", "type": "Informational"}, {"address": 276, "code": "* c +", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TeamAmberInterface_4: 0x1\ncalldata_TeamAmberInterface_0: 0x3ce6c5500000000000000000000000000000000000000000000000000000000\ncalldatasize_TeamAmberInterface: 0x4\ncalldata_TeamAmberInterface_32 + 4: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Amber_Game-0.sol", "function": "roundUp(uint256,uint256)", "lineno": 30, "title": "Exception state", "type": "Informational"}], "success": true}
