{"error": null, "issues": [{"address": 254, "code": " ResultCode {\n        SUCCESS,", "debug": "The exception is triggered under the following conditions:\n\ncalldata_SafeMath_32 + 4: 0x0\ncalldata_SafeMath_4: 0xffff\ncalldata_SafeMath_0: 0x6216123500000000000000000000000000000000000000000000000000000000\ncalldatasize_SafeMath: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Angel_Battles-11.sol", "function": "getRandomNumber(uint16,uint8,address)", "lineno": 77, "title": "Exception state", "type": "Informational"}], "success": true}
