{"error": null, "issues": [{"address": 1895, "code": "sterUser(strin", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\nstorage_3: 0x0\ncalldata_UserToken_0: 0x5d8d158500000000000000000000000000000000000000000000000000000000\ncalldatasize_UserToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Crypto_Ninja-5.sol", "function": "getUserInfo()", "lineno": 2567, "title": "Exception state", "type": "Informational"}, {"address": 4120, "code": "ss _ninjaToke", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x1\nstorage_3: 0x1\ncalldata_UserToken_4 + calldata_UserToken_4: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_0: 0x0\ncalldata_UserToken_0: 0xc47f002700000000000000000000000000000000000000000000000000000000\ncalldatasize_UserToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Crypto_Ninja-5.sol", "function": "setName(string)", "lineno": 2549, "title": "Exception state", "type": "Informational"}], "success": true}
