{"error": null, "issues": [{"address": 431, "code": "ction getApproved(uint256 _to", "debug": "The exception is triggered under the following conditions:\n\ncalldata_StringLib_32 + 36: 0x1\ncalldata_StringLib_0: 0x206b64b400000000000000000000000000000000000000000000000000000000\ncalldatasize_StringLib: 0x4\n2_EXP_8*calldata_StringLib_32 + 4: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Crypto_Ninja-0.sol", "function": "generateName(bytes16,uint256,uint256)", "lineno": 847, "title": "Exception state", "type": "Informational"}], "success": true}
