{"error": null, "issues": [{"address": 890, "code": " whenNotPaused\n  {\n    require(_maker != msg.sende", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_115792089237316195423570985008687907853269984665640564039457584007913129639935_-\n0_&\ncalldata_StrikersTrading_4: 0x8000\ncalldata_StrikersTrading_0: 0x1b9ad23900000000000000000000000000000000000000000000000000000000\ncalldatasize_StrikersTrading: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/CryptoStrikers-3.sol", "function": "_function_0x1b9ad239", "lineno": 1489, "title": "Exception state", "type": "Informational"}], "success": true}
