{"error": null, "issues": [{"address": 579, "code": "ctionSuccessful(uint256 toke", "debug": "The exception is triggered under the following conditions:\n\ncalldata_WarriorTokenImpl_4: 0x13\ncalldata_WarriorTokenImpl_0: 0x2a4a9dd100000000000000000000000000000000000000000000000000000000\ncalldatasize_WarriorTokenImpl: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ether_Quest-4.sol", "function": "_function_0x2a4a9dd1", "lineno": 3361, "title": "Exception state", "type": "Informational"}], "success": true}
