{"error": null, "issues": [{"address": 648, "code": "   wh", "debug": "calldata_Utils_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Utils_0: 0x677342ce00000000000000000000000000000000000000000000000000000000\ncalldatasize_Utils: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `sqrt(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Ethecom-0.sol", "function": "sqrt(uint256)", "lineno": 35, "title": "Integer Overflow ", "type": "Warning"}, {"address": 688, "code": " func", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Utils_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Utils_0: 0x677342ce00000000000000000000000000000000000000000000000000000000\ncalldatasize_Utils: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Ethecom-0.sol", "function": "sqrt(uint256)", "lineno": 41, "title": "Exception state", "type": "Informational"}], "success": true}
