{"error": null, "issues": [{"address": 3047, "code": ".owner);\n    ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_HumanityCard_4: 0x0\nstorage_3: 0x0\nstorage_2: 0x1\ncalldata_HumanityCard_0: 0x1dd7cf6d00000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Humanity_Cards-0.sol", "function": "getHumanInfo(uint256)", "lineno": 374, "title": "Exception state", "type": "Informational"}, {"address": 3461, "code": "\n\ncontract ERC721 ", "debug": "storage_9: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_HumanityCard_4: 0x0\nstorage_0 +\n111414077815863400510004064629973595961579173665589224203503662149373724986687 +\n2*calldata_HumanityCard_4: 0x0\ncaller: 0x0\nstorage_6: 0x1\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x1df6810200000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `createSellOrder(uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Humanity_Cards-0.sol", "function": "createSellOrder(uint256,uint256)", "lineno": 1, "title": "Integer Overflow ", "type": "Warning"}, {"address": 3758, "code": "dexUser;\n    }\n\n    functi", "debug": "calldata_HumanityCard_4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\nstorage_0 +\n111414077815863400510004064629973595961579173665589224203503662149373724986687 +\n2*calldata_HumanityCard_4: 0x0\ncaller: 0x0\nstorage_6: 0x1\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x1df6810200000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `createSellOrder(uint256,uint256)`.\nThe subtraction may result in a value < 0.", "filename": "/temp/Humanity_Cards-0.sol", "function": "createSellOrder(uint256,uint256)", "lineno": 283, "title": "Integer Underflow", "type": "Warning"}, {"address": 4563, "code": "[_from]];\n        car", "debug": "calldata_HumanityCard_32 + 36: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_HumanityCard_4: 0x0\nstorage_keccac_calldata_HumanityCard_32_+_36: 0x0\ncalldata_HumanityCard_32 + 4: 0x0\nstorage_0 +\n111414077815863400510004064629973595961579173665589224203503662149373724986687 +\n2*calldata_HumanityCard_32 + 36: 0xffffffffffffffffffffffffffffffffffffffff00\ncalldata_HumanityCard_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_6: 0x1\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `transferFrom(address,address,uint256)`.\nThe subtraction may result in a value < 0.", "filename": "/temp/Humanity_Cards-0.sol", "function": "transferFrom(address,address,uint256)", "lineno": 153, "title": "Integer Underflow", "type": "Warning"}, {"address": 6081, "code": ".sender == ownerOf(", "debug": "The exception is triggered under the following conditions:\n\ncalldata_HumanityCard_4: 0x0\nstorage_6: 0x0\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x6352211e00000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Humanity_Cards-0.sol", "function": "ownerOf(uint256)", "lineno": 138, "title": "Exception state", "type": "Informational"}, {"address": 6177, "code": "() public payable r", "debug": "The exception is triggered under the following conditions:\n\ncalldata_HumanityCard_4: 0x0\nstorage_6: 0x0\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x6914db6000000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Humanity_Cards-0.sol", "function": "tokenMetadata(uint256)", "lineno": 228, "title": "Exception state", "type": "Informational"}, {"address": 6230, "code": "       require(msg.", "debug": "The exception is triggered under the following conditions:\n\nstorage_3: 0x0\ncalldata_HumanityCard_4: 0x0\nstorage_0 +\n111414077815863400510004064629973595961579173665589224203503662149373724986687 +\n2*calldata_HumanityCard_4: 0x0\nstorage_6: 0x1\nstorage_5: 0x1\ncalldata_HumanityCard_0: 0x6914db6000000000000000000000000000000000000000000000000000000000\ncalldatasize_HumanityCard: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Humanity_Cards-0.sol", "function": "tokenMetadata(uint256)", "lineno": 229, "title": "Exception state", "type": "Informational"}], "success": true}
