{"error": null, "issues": [{"address": 175, "code": "            msg.", "debug": "callvalue: 0x200024448e041042b936adc03422252c124014908019505c2524442448d00412\nstorage_0: 0xff00\ncalldata_lucky9io_0: 0x7c428d4500000000000000000000000000000000000000000000000000000000\ncalldatasize_lucky9io: 0x4\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 26, "title": "Integer Overflow ", "type": "Warning"}, {"address": 262, "code": "ue = address(thi", "debug": "callvalue: 0x1070a0cbba124955178113fb42bb7fffebaafdd16b6294a4a4410100ea6e5cb6\nstorage_1: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_0: 0xff00\ncalldata_lucky9io_0: 0x7c428d4500000000000000000000000000000000000000000000000000000000\ncalldatasize_lucky9io: 0x4\n", "description": "A possible integer overflow exists in the function `fallback`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 31, "title": "Integer Overflow ", "type": "Warning"}, {"address": 387, "code": "0);\n            owner.transfer(valu", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 509\n", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 34, "title": "Multiple Calls", "type": "Information"}, {"address": 509, "code": "            return;\n        }\n\n ", "debug": "", "description": "A possible transaction order independence vulnerability exists in function fallback. The value or direction of the call statement is determined from a tainted storage location", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 36, "title": "Transaction order dependence", "type": "Warning"}, {"address": 616, "code": "      owner.transfer(0.03 ether", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 728\n", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 41, "title": "Multiple Calls", "type": "Information"}, {"address": 834, "code": "owner.transfer(0.01 ether);\n   ", "debug": "", "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 946\n", "filename": "/temp/lucky9.io-0.sol", "function": "fallback", "lineno": 47, "title": "Multiple Calls", "type": "Information"}, {"address": 1328, "code": "address(this).balance);\n    }\n\n    fu", "debug": "", "description": "A possible transaction order independence vulnerability exists in function stopGame(). The value or direction of the call statement is determined from a tainted storage location", "filename": "/temp/lucky9.io-0.sol", "function": "stopGame()", "lineno": 16, "title": "Transaction order dependence", "type": "Warning"}], "success": true}
