{"error": null, "issues": [{"address": 1300, "code": "        require(tokenIdToOwner[_tokenId] == address(this));\n        require(_to != address(0));\n\n        _transfer(address(this), _to, _tokenId);\n    }\n\n    /// @d", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WonderToken_4: 0x800000000000000000000000000000000000000000000000000000000000000\ncalldata_WonderToken_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_WonderToken_0: 0x3a562b7800000000000000000000000000000000000000000000000000000000\ncalldatasize_WonderToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getOwnTokens(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Token_Tycoon-4.sol", "function": "getOwnTokens(address)", "lineno": 392, "title": "Integer Overflow ", "type": "Warning"}, {"address": 7229, "code": "(this), _to, _tokenId);\n    }\n\n  ", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WonderToken_4: 0x8421003f084001f4210815cf88407c00000000000000037c1d000e8d178001f\ncalldata_WonderToken_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_WonderToken_0: 0x3a562b7800000000000000000000000000000000000000000000000000000000\ncalldatasize_WonderToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getOwnTokens(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Token_Tycoon-4.sol", "function": "getOwnTokens(address)", "lineno": 395, "title": "Integer Overflow ", "type": "Warning"}, {"address": 7231, "code": "(this), _to, _tokenId);\n    }\n\n  ", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WonderToken_4: 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb\ncalldata_WonderToken_4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_WonderToken_0: 0x3a562b7800000000000000000000000000000000000000000000000000000000\ncalldatasize_WonderToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `getOwnTokens(address)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/temp/Token_Tycoon-4.sol", "function": "getOwnTokens(address)", "lineno": 395, "title": "Integer Overflow ", "type": "Warning"}, {"address": 7555, "code": "dress) tokenIdToOwner;\n    /", "debug": "The exception is triggered under the following conditions:\n\ncalldata_WonderToken_4: 0x0\nstorage_1: 0x0\ncalldata_WonderToken_0: 0x5ce8e0fc00000000000000000000000000000000000000000000000000000000\ncalldatasize_WonderToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Token_Tycoon-4.sol", "function": "_function_0x5ce8e0fc", "lineno": 106, "title": "Exception state", "type": "Informational"}, {"address": 11616, "code": "        \n          ", "debug": "The exception is triggered under the following conditions:\n\ncalldata_WonderToken_4: 0x1\nstorage_keccac_calldata_WonderToken_4: 0xc00000000000000000000000000000000000000000\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\nUDiv(storage_keccac_calldata_WonderToken_4,_256): 0xc00000000000000000000000000000000000000000\ncalldata_WonderToken_32 + 4: 0x4000000000000000000000000000000000000000\nstorage_1: 0x1\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xff00\nstorage_0: 0x0\ncalldata_WonderToken_0: 0x18ad052b00000000000000000000000000000000000000000000000000000000\ncalldatasize_WonderToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/temp/Token_Tycoon-4.sol", "function": "safeTransferByContract(uint256,address)", "lineno": 332, "title": "Exception state", "type": "Informational"}], "success": true}
